export const ironcladCards = [
  {
    name: 'Bash',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Common',
    cost: '2',
    desc: 'Deal 8(10) damage. Apply 2(3) Vulnerable.',
  },
  {
    name: 'Defend',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Common',
    cost: '1',
    desc: 'Gain 5(8) Block.',
  },
  {
    name: 'Strike',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Common',
    cost: '1',
    desc: 'Deal 6(9) damage.',
  },
  {
    name: 'Anger',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Common',
    cost: '0',
    desc: 'Deal 6(8) damage. Add a copy of this card to your discard pile.',
  },
  {
    name: 'Armaments',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Common',
    cost: '1',
    desc: 'Gain 5 Block. Upgrade a(ALL) card(s) in your hand for the rest of combat.',
  },
  {
    name: 'Body Slam',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Common',
    cost: '1(0)',
    desc: 'Deal damage equal to your current Block.',
  },
  {
    name: 'Clash',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Common',
    cost: '0',
    desc: 'Can only be played if every card in your hand is an Attack. Deal 14(18) damage.',
  },
  {
    name: 'Cleave',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Common',
    cost: '1',
    desc: 'Deal 8(11) damage to ALL enemies.',
  },
  {
    name: 'Clothesline',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Common',
    cost: '2',
    desc: 'Deal 12(14) damage. Apply 2(3) Weak.',
  },
  {
    name: 'Flex',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Common',
    cost: '0',
    desc: 'Gain 2(4) Strength. At the end of your turn, lose 2(4) Strength.',
  },
  {
    name: 'Havoc',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Common',
    cost: '1(0)',
    desc: 'Play the top card of your draw pile and Exhaust it.',
  },
  {
    name: 'Headbutt',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Common',
    cost: '1',
    desc: 'Deal 9(12) damage. Place a card from your discard pile on top of your draw pile.',
  },
  {
    name: 'Heavy Blade',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Common',
    cost: '2',
    desc: 'Deal 14 damage. Strength affects Heavy Blade 3(5) times.',
  },
  {
    name: 'Iron Wave',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Common',
    cost: '1',
    desc: 'Gain 5(7) Block. Deal 5(7) damage.',
  },
  {
    name: 'Perfected Strike',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Common',
    cost: '2',
    desc: 'Deal 6 damage. Deals an additional 2(3) damage for ALL of your cards containing "Strike".',
  },
  {
    name: 'Pommel Strike',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Common',
    cost: '1',
    desc: 'Deal 9(10) damage. Draw 1(2) card(s).',
  },
  {
    name: 'Shrug it Off',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Common',
    cost: '1',
    desc: 'Gain 8(11) Block. Draw 1 card.',
  },
  {
    name: 'Sword Boomerang',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Common',
    cost: '1',
    desc: 'Deal 3 damage to a random enemy 3(4) times.',
  },
  {
    name: 'Thunderclap',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Common',
    cost: '1',
    desc: 'Deal 4(7) damage and apply 1 Vulnerable to ALL enemies.',
  },
  {
    name: 'True Grit',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Common',
    cost: '1',
    desc: 'Gain 7(9) Block. Exhaust a random(not random) card from your hand.',
  },
  {
    name: 'Twin Strike',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Common',
    cost: '1',
    desc: 'Deal 5(7) damage twice.',
  },
  {
    name: 'Warcry',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Common',
    cost: '0',
    desc: 'Draw 1(2) card(s). Place a card from your hand on top of your draw pile. Exhaust.',
  },
  {
    name: 'Wild Strike',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Common',
    cost: '1',
    desc: 'Deal 12(17) damage. Shuffle a Wound into your draw pile.',
  },
  {
    name: 'Battle Trance',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '0',
    desc: 'Draw 3(4) cards. You cannot draw additional cards this turn.',
  },
  {
    name: 'Blood for Blood',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Uncommon',
    cost: '4(3)',
    desc: 'Costs 1 less energy for each time you lose HP in combat. Deal 18(22) damage.',
  },
  {
    name: 'Bloodletting',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '0',
    desc: 'Lose 3 HP. Gain 2(3) Energy.',
  },
  {
    name: 'Burning Pact',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '1',
    desc: 'Exhaust 1 card. Draw 2(3) cards.',
  },
  {
    name: 'Carnage',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Uncommon',
    cost: '2',
    desc: 'Ethereal. Deal 20(28) damage.',
  },
  {
    name: 'Combust',
    category: 'ironclad',
    type: 'Power',
    rarity: 'Uncommon',
    cost: '1',
    desc: 'At the end of your turn, lose 1 HP and deal 5(7) damage to ALL enemies.',
  },
  {
    name: 'Dark Embrace',
    category: 'ironclad',
    type: 'Power',
    rarity: 'Uncommon',
    cost: '2(1)',
    desc: 'Whenever a card is Exhausted, draw 1 card.',
  },
  {
    name: 'Disarm',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '1',
    desc: 'Enemy loses 2(3) Strength. Exhaust.',
  },
  {
    name: 'Dropkick',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Uncommon',
    cost: '1',
    desc: 'Deal 5(8) damage. If the enemy is Vulnerable, gain 1 energy and draw 1 card.',
  },
  {
    name: 'Dual Wield',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '1',
    desc: 'Create a(2) copy(s) of an Attack or Power card in your hand.',
  },
  {
    name: 'Entrench',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '2(1)',
    desc: 'Double your current Block.',
  },
  {
    name: 'Evolve',
    category: 'ironclad',
    type: 'Power',
    rarity: 'Uncommon',
    cost: '1',
    desc: 'Whenever you draw a Status card, draw 1(2) card(s).',
  },
  {
    name: 'Feel No Pain',
    category: 'ironclad',
    type: 'Power',
    rarity: 'Uncommon',
    cost: '1',
    desc: 'Whenever a card is Exhausted, gain 3(4) Block.',
  },
  {
    name: 'Fire Breathing',
    category: 'ironclad',
    type: 'Power',
    rarity: 'Uncommon',
    cost: '1',
    desc: 'Whenever you draw a Status or Curse card, deal 6(10) damage to all enemies.',
  },
  {
    name: 'Flame Barrier',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '2',
    desc: 'Gain 12(16) Block. Whenever you are attacked this turn, deal 4(6) damage to the attacker.',
  },
  {
    name: 'Ghostly Armor',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '1',
    desc: 'Ethereal. Gain 10(13) Block.',
  },
  {
    name: 'Hemokinesis',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Uncommon',
    cost: '1',
    desc: 'Lose 2 HP. Deal 15(20) damage.',
  },
  {
    name: 'Infernal Blade',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '1(0)',
    desc: 'Add a random Attack to your hand. It costs 0 this turn. Exhaust.',
  },
  {
    name: 'Inflame',
    category: 'ironclad',
    type: 'Power',
    rarity: 'Uncommon',
    cost: '1',
    desc: 'Gain 2(3) Strength.',
  },
  {
    name: 'Intimidate',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '0',
    desc: 'Apply 1(2) Weak to ALL enemies. Exhaust.',
  },
  {
    name: 'Metallicize',
    category: 'ironclad',
    type: 'Power',
    rarity: 'Uncommon',
    cost: '1',
    desc: 'At the end of your turn, gain 3(4) Block.',
  },
  {
    name: 'Power Through',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '1',
    desc: 'Add 2 Wounds to your hand. Gain 15(20) Block.',
  },
  {
    name: 'Pummel',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Uncommon',
    cost: '1',
    desc: 'Deal 2 damage 4(5) times. Exhaust.',
  },
  {
    name: 'Rage',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '0',
    desc: 'Whenever you play an Attack this turn, gain 3(5) Block.',
  },
  {
    name: 'Rampage',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Uncommon',
    cost: '1',
    desc: "Deal 8 damage. Increase this card's damage by 5(8) this combat.",
  },
  {
    name: 'Reckless Charge',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Uncommon',
    cost: '0',
    desc: 'Deal 7(10) damage. Shuffle a Dazed into your draw pile.',
  },
  {
    name: 'Rupture',
    category: 'ironclad',
    type: 'Power',
    rarity: 'Uncommon',
    cost: '1',
    desc: 'Whenever you lose HP from a card, gain 1(2) Strength.',
  },
  {
    name: 'Searing Blow',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Uncommon',
    cost: '2',
    desc: 'Deal 12(16) damage. Can be upgraded any number of times.',
  },
  {
    name: 'Second Wind',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '1',
    desc: 'Exhaust all non-Attack cards in your hand and gain 5(7) Block for each card Exhausted.',
  },
  {
    name: 'Seeing Red',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '1(0)',
    desc: 'Gain 2 energy. Exhaust.',
  },
  {
    name: 'Sentinel',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '1',
    desc: 'Gain 5(8) Block. If this card is Exhausted, gain 2(3) energy.',
  },
  {
    name: 'Sever Soul',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Uncommon',
    cost: '2',
    desc: 'Exhaust all non-Attack cards in your hand. Deal 16(22) damage.',
  },
  {
    name: 'Shockwave',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '2',
    desc: 'Apply 3(5) Weak and Vulnerable to ALL enemies. Exhaust.',
  },
  {
    name: 'Spot Weakness',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '1',
    desc: 'If the enemy intends to attack, gain 3(4) Strength.',
  },
  {
    name: 'Uppercut',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Uncommon',
    cost: '2',
    desc: 'Deal 13 damage. Apply 1(2) Weak. Apply 1(2) Vulnerable.',
  },
  {
    name: 'Whirlwind',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Uncommon',
    cost: 'X',
    desc: 'Deal 5(8) damage to ALL enemies X times.',
  },
  {
    name: 'Barricade',
    category: 'ironclad',
    type: 'Power',
    rarity: 'Rare',
    cost: '3(2)',
    desc: 'Block is not removed at the start of your turn.',
  },
  {
    name: 'Berserk',
    category: 'ironclad',
    type: 'Power',
    rarity: 'Rare',
    cost: '0',
    desc: 'Gain 2(1) Vulnerable. At the start of your turn, gain 1 Energy.',
  },
  {
    name: 'Bludgeon',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Rare',
    cost: '3',
    desc: 'Deal 32(42) damage.',
  },
  {
    name: 'Brutality',
    category: 'ironclad',
    type: 'Power',
    rarity: 'Rare',
    cost: '0',
    desc: '(Innate.) At the start of your turn, lose 1 HP and draw 1 card.',
  },
  {
    name: 'Corruption',
    category: 'ironclad',
    type: 'Power',
    rarity: 'Rare',
    cost: '3(2)',
    desc: 'Skills cost 0. Whenever you play a Skill, Exhaust it.',
  },
  {
    name: 'Demon Form',
    category: 'ironclad',
    type: 'Power',
    rarity: 'Rare',
    cost: '3',
    desc: 'At the start of each turn, gain 2(3) Strength.',
  },
  {
    name: 'Double Tap',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Rare',
    cost: '1',
    desc: 'This turn, your next (2) Attack(s) is(are) played twice.',
  },
  {
    name: 'Exhume',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Rare',
    cost: '1(0)',
    desc: 'Put a card from your Exhaust pile into your hand. Exhaust.',
  },
  {
    name: 'Feed',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Rare',
    cost: '1',
    desc: 'Deal 10(12) damage. If this kills a non-minion enemy, gain 3(4) permanent Max HP. Exhaust.',
  },
  {
    name: 'Fiend Fire',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Rare',
    cost: '2',
    desc: 'Exhaust all cards in your hand. Deal 7(10) damage for each Exhausted card. Exhaust.',
  },
  {
    name: 'Immolate',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Rare',
    cost: '2',
    desc: 'Deal 21(28) damage to ALL enemies. Add a Burn into your discard pile.',
  },
  {
    name: 'Impervious',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Rare',
    cost: '2',
    desc: 'Gain 30(40) Block. Exhaust.',
  },
  {
    name: 'Juggernaut',
    category: 'ironclad',
    type: 'Power',
    rarity: 'Rare',
    cost: '2',
    desc: 'Whenever you gain Block, deal 5(7) damage to a random enemy.',
  },
  {
    name: 'Limit Break',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Rare',
    cost: '1',
    desc: "Double your Strength. Exhaust(Don't Exhaust).",
  },
  {
    name: 'Offering',
    category: 'ironclad',
    type: 'Skill',
    rarity: 'Rare',
    cost: '0',
    desc: 'Lose 6 HP. Gain 2 energy. Draw 3(5) cards. Exhaust.',
  },
  {
    name: 'Reaper',
    category: 'ironclad',
    type: 'Attack',
    rarity: 'Rare',
    cost: '2',
    desc: 'Deal 4(5) damage to ALL enemies. Heal HP equal to unblocked damage. Exhaust.',
  },
];
