export const colorlessCards = [
  {
    name: 'Bandage Up',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '0',
    desc: 'Heal 4(6) HP. Exhaust.',
  },
  {
    name: 'Blind',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '0',
    desc: 'Apply 2 Weak (to ALL enemies).',
  },
  {
    name: 'Dark Shackles',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '0',
    desc: 'Enemy loses 9(15) Strength for the rest of this turn. Exhaust.',
  },
  {
    name: 'Deep Breath',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '0',
    desc: 'Shuffle your discard pile into your draw pile. Draw 1(2) card(s).',
  },
  {
    name: 'Discovery',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '1',
    desc: "Choose 1 of 3 random cards to add to your hand. It costs 0 this turn. Exhaust. (Don't Exhaust.)",
  },
  {
    name: 'Dramatic Entrance',
    category: 'colorless',
    type: 'Attack',
    rarity: 'Uncommon',
    cost: '0',
    desc: 'Innate. Deal 8(12) damage to ALL enemies. Exhaust.',
  },
  {
    name: 'Enlightenment',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '0',
    desc: 'Reduce the cost of cards in your hand to 1 this turn(combat).',
  },
  {
    name: 'Finesse',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '0',
    desc: 'Gain 2(4) Block. Draw 1 card.',
  },
  {
    name: 'Flash of Steel',
    category: 'colorless',
    type: 'Attack',
    rarity: 'Uncommon',
    cost: '0',
    desc: 'Deal 3(6) damage. Draw 1 card.',
  },
  {
    name: 'Forethought',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '0',
    desc:
      'Place a card(any number of cards) from your hand on the bottom of your draw pile. It (They) costs 0 until played.',
  },
  {
    name: 'Good Instincts',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '0',
    desc: 'Gain 6(9) Block.',
  },
  {
    name: 'Impatience',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '0',
    desc: 'If you have no Attack cards in your hand, draw 2(3) cards.',
  },
  {
    name: 'Jack Of All Trades',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '0',
    desc: 'Add 1(2) random Colorless card(s) to your hand. Exhaust.',
  },
  {
    name: 'Madness',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '1(0)',
    desc: 'A random card in your hand costs 0 for the rest of combat. Exhaust.',
  },
  {
    name: 'Mind Blast',
    category: 'colorless',
    type: 'Attack',
    rarity: 'Uncommon',
    cost: '2(1)',
    desc: 'Innate. Deal damage equal to the number of cards in your draw pile.',
  },
  {
    name: 'Panacea',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '0',
    desc: 'Gain 1(2) Artifact. Exhaust.',
  },
  {
    name: 'Panic Button',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '0',
    desc: 'Gain 30(40) Block. You cannot gain Block from cards for the next 2 turns. Exhaust.',
  },
  {
    name: 'Purity',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '0',
    desc: 'Choose and exhaust 3(5) cards in your hand. Exhaust.',
  },
  {
    name: 'Swift Strike',
    category: 'colorless',
    type: 'Attack',
    rarity: 'Uncommon',
    cost: '0',
    desc: 'Deal 7(10) damage.',
  },
  {
    name: 'Trip',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Uncommon',
    cost: '0',
    desc: 'Apply 2 Vulnerable (to ALL enemies).',
  },
  {
    name: 'Apotheosis',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Rare',
    cost: '2(1)',
    desc: 'Upgrade ALL of your cards for the rest of combat. Exhaust.',
  },
  {
    name: 'Chrysalis',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Rare',
    cost: '2',
    desc: 'Add 3(5) random Skills into your Draw Pile. They cost 0 this combat. Exhaust.',
  },
  {
    name: 'Hand of Greed',
    category: 'colorless',
    type: 'Attack',
    rarity: 'Rare',
    cost: '2',
    desc: 'Deal 20(25) damage. If this kills a non-minion enemy, gain 20(25) Gold.',
  },
  {
    name: 'Magnetism',
    category: 'colorless',
    type: 'Power',
    rarity: 'Rare',
    cost: '2(1)',
    desc: 'At the start of each turn, add a random colorless card to your hand.',
  },
  {
    name: 'Master Of Strategy',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Rare',
    cost: '0',
    desc: 'Draw 3(4) cards. Exhaust.',
  },
  {
    name: 'Mayhem',
    category: 'colorless',
    type: 'Power',
    rarity: 'Rare',
    cost: '2(1)',
    desc: 'At the start of your turn, play the top card of your draw pile.',
  },
  {
    name: 'Metamorphosis',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Rare',
    cost: '2',
    desc: 'Add 3(5) random Attacks into your Draw Pile. They cost 0 this combat. Exhaust.',
  },
  {
    name: 'Panache',
    category: 'colorless',
    type: 'Power',
    rarity: 'Rare',
    cost: '0',
    desc: 'Every time you play 5 cards in a single turn, deal 10(14) damage to ALL enemies.',
  },
  {
    name: 'Sadistic Nature',
    category: 'colorless',
    type: 'Power',
    rarity: 'Rare',
    cost: '0',
    desc: 'Whenever you apply a Debuff to an enemy, they take 5(7) damage.',
  },
  {
    name: 'Secret Technique',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Rare',
    cost: '0',
    desc: "Choose a Skill from your draw pile and place it into your hand. Exhaust. (Don't Exhaust)",
  },
  {
    name: 'Secret Weapon',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Rare',
    cost: '0',
    desc: "Choose an Attack from your draw pile and place it into your hand. Exhaust. (Don't Exhaust)",
  },
  {
    name: 'The Bomb',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Rare',
    cost: '2',
    desc: 'At the end of 3 turns, deal 40(50) damage to ALL enemies.',
  },
  {
    name: 'Thinking Ahead',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Rare',
    cost: '0',
    desc: "Draw 2 cards. Place a card from your hand on top of your draw pile. Exhaust. (Don't Exhaust)",
  },
  {
    name: 'Transmutation',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Rare',
    cost: 'X',
    desc: 'Add X random (Upgraded) colorless cards into your hand. They cost 0 this turn. Exhaust.',
  },
  {
    name: 'Violence',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Rare',
    cost: '0',
    desc: 'Place 3(4) random Attack cards from your draw pile into your hand. Exhaust.',
  },
  {
    name: 'Apparition',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Special',
    cost: '1',
    desc: 'Gain 1 Intangible. Exhaust. Ethereal. (no longer Ethereal.) (Obtained from event: Council of Ghosts).',
  },
  {
    name: 'Beta',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Special',
    cost: '2(1)',
    desc: 'Shuffle an Omega into your draw pile. Exhaust.(Obtained from Alpha).',
  },
  {
    name: 'Bite',
    category: 'colorless',
    type: 'Attack',
    rarity: 'Special',
    cost: '1',
    desc: 'Deal 7(8) damage. Heal 2(3) HP. (Obtained from event: Vampires(?)).',
  },
  {
    name: 'Expunger',
    category: 'colorless',
    type: 'Attack',
    rarity: 'Special',
    cost: '1',
    desc: 'Deal 9(15) damage X times. (Obtained from Conjure Blade).',
  },
  {
    name: 'Insight',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Special',
    cost: '0',
    desc: 'Retain. Draw 2(3) cards. Exhaust. (Obtained from Evaluate, Pray and Study).',
  },
  {
    name: 'J.A.X.',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Special',
    cost: '0',
    desc: 'Lose 3 HP. Gain 2(3)  Strength.(Obtained from event: Augmenter).',
  },
  {
    name: 'Miracle',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Special',
    cost: '0',
    desc: 'Retain. Gain (2) Energy. Exhaust. (Obtained from Collect, Deus Ex Machina,  Pure Water, and  Holy Water).',
  },
  {
    name: 'Omega',
    category: 'colorless',
    type: 'Power',
    rarity: 'Special',
    cost: '3',
    desc: 'At the end of your turn deal 50(60) damage to ALL enemies. (Obtained from Beta).',
  },
  {
    name: 'Ritual Dagger',
    category: 'colorless',
    type: 'Attack',
    rarity: 'Special',
    cost: '1',
    desc:
      "Deal 15 damage. If this kills an enemy then permanently increase this card's damage by 3(5). Exhaust. (Obtained during event: The Nest)",
  },
  {
    name: 'Safety',
    category: 'colorless',
    type: 'Skill',
    rarity: 'Special',
    cost: '1',
    desc: 'Retain. Gain 12(16) Block. Exhaust. (Obtained from Deceive Reality).',
  },
  {
    name: 'Shiv',
    category: 'colorless',
    type: 'Attack',
    rarity: 'Special',
    cost: '0',
    desc:
      'Deal 4(6) damage. Exhaust. (Obtained from Blade Dance, Cloak and Dagger, Infinite Blades, Storm of Steel, and  Ninja Scroll).',
  },
  {
    name: 'Smite',
    category: 'colorless',
    type: 'Attack',
    rarity: 'Special',
    cost: '1',
    desc: 'Retain. Deal 12(16) damage. Exhaust. (Obtained from Carve Reality and Battle Hymn).',
  },
  {
    name: 'Through Violence',
    category: 'colorless',
    type: 'Attack',
    rarity: 'Special',
    cost: '0',
    desc: 'Retain. Deal 20(30) damage. Exhaust. (Obtained from Reach Heaven).',
  },
];
